services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: ""
    startCommand: gunicorn codezbin_server.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: codezbin_server.settings
